from building import *

cwd = GetCurrentDir()
src	= []
inc = []

src += Glob('*.c')
src += Glob('lib/*.c')
src += Glob('lib/*.cpp')

inc += [cwd]
inc += [cwd + '/lib']

group = DefineGroup('APM_LIB', src, depend = [''], CPPPATH = inc, CPPDEFINES=['APM_STANDALONE'])

Return('group')
